name: "CI/CD Pipeline"
on: 
  push:
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Snyk to check for vulnerabilities
      #test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          
      - name: Monitor project with Snyk
      #monitor
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
