name: snyk
on:
  push:
    branches:
      - master
      
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: Install snyk
        run: npm install -g snyk

      - name: Configure Snyk endpoint
        run: snyk config set endpoint=https://api.us.snyk.io

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

  snyk-code:
    environment: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: snyk/actions/setup@master
      - name: Configure Snyk endpoint
        run: snyk config set endpoint=https://api.us.snyk.io
      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk code test --severity-threshold=critical --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Code Test
        continue-on-error: true
        run: snyk monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
